#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/^\(listen\s\+\).*$/\180;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
