#!/usr/bin/env bash
# This is a Bash Script that installs and configures HAProxy on the lb-01 Load Balancer server
# to send traffic to web-server web-01 and web-server web-02 using the RoundRobin algorithm

sudo apt update && sudo apt upgrade -y

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install haproxy=2.7.*

# Editing the configuration file
server_config='
frontend webapp-frontend
    bind *:80
    mode http
    default_backend webapp-backend

backend webapp-backend
    balance roundrobin
    server 221261-web-01 34.227.101.95:80 check
    server 221261-web-02 54.90.5.101:80 check
'

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
