#!/usr/bin/env bash
#Pings an IP address received as a string argument 5 times
#If executed without any arguments, it displays a message explaining the correct argument format.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
